services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloakdb
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak-container
    restart: unless-stopped
    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql:3306/keycloakdb
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: szarvas
      KEYCLOAK_ADMIN_PASSWORD: szarvas
    ports:
      - "8080:8080"
    command: ["start-dev"]
    depends_on:
      - mysql
    networks:
      - keycloak-network

  spring-backend:
    build:
      context: ../backend
    container_name: spring-app-container
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: jdbc:mysql://mysql-container:3306/szarvaspc
      DATABASE_USERNAME: api
      DATABASE_PASSWORD: api
    depends_on:
      - mysql
      - keycloak
    networks:
      - keycloak-network

volumes:
  mysql-data:

networks:
  keycloak-network:
